# This program has been developed by students from the bachelor Computer Science at
# Utrecht University within the Software Project course.
# © Copyright Utrecht University (Department of Information and Computing Sciences)

image-build:
  image: docker
  stage: build
  rules:
    - changes:
        - PipelineDockerfile
  script:
    - docker build -f PipelineDockerfile -t controller-ci-image:$CI_COMMIT_REF_NAME .

variables:
  GIT_SUBMODULE_STRATEGY: recursive

google-tests:
  image: controller-ci-image:$CI_COMMIT_REF_NAME
  stage: test
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  script:
    - mkdir controller_test_build
    - cd controller_test_build
    - cmake ../tests
    - cmake --build .
    - ./controller_tests --gtest_output="xml:report.xml"


linting:
  image: controller-ci-image:$CI_COMMIT_REF_NAME
  stage: test
  variables:
    DEBIAN_FRONTEND: noninteractive
  script:
    - cd libSearchSECOController
    - clang-tidy *.cpp --extra-arg=-std=c++20 -- -I../parser/libSearchSECOParser/ -I../spider-revisited/libSearchSECOSpider/ -I../crawler/libSearchSECOCrawler/
    - clang *.cpp -I../parser/libSearchSECOParser/ -I../spider-revisited/libSearchSECOSpider/ -I../crawler/libSearchSECOCrawler/ -fsyntax-only -std=c++20