var namespaces_dup =
[
    [ "antlr4", null, [
      [ "atn", null, [
        [ "AbstractPredicateTransition", "classantlr4_1_1atn_1_1AbstractPredicateTransition.html", null ],
        [ "ActionTransition", "classantlr4_1_1atn_1_1ActionTransition.html", "classantlr4_1_1atn_1_1ActionTransition" ],
        [ "ArrayPredictionContext", "classantlr4_1_1atn_1_1ArrayPredictionContext.html", "classantlr4_1_1atn_1_1ArrayPredictionContext" ],
        [ "ATNConfig", "classantlr4_1_1atn_1_1ATNConfig.html", "classantlr4_1_1atn_1_1ATNConfig" ],
        [ "ATNConfigSet", "classantlr4_1_1atn_1_1ATNConfigSet.html", "classantlr4_1_1atn_1_1ATNConfigSet" ],
        [ "ATNDeserializationOptions", "classantlr4_1_1atn_1_1ATNDeserializationOptions.html", null ],
        [ "ATNDeserializer", "classantlr4_1_1atn_1_1ATNDeserializer.html", null ],
        [ "ATNSerializer", "classantlr4_1_1atn_1_1ATNSerializer.html", "classantlr4_1_1atn_1_1ATNSerializer" ],
        [ "ATNSimulator", "classantlr4_1_1atn_1_1ATNSimulator.html", "classantlr4_1_1atn_1_1ATNSimulator" ],
        [ "AtomTransition", "classantlr4_1_1atn_1_1AtomTransition.html", "classantlr4_1_1atn_1_1AtomTransition" ],
        [ "BasicBlockStartState", "classantlr4_1_1atn_1_1BasicBlockStartState.html", null ],
        [ "BasicState", "classantlr4_1_1atn_1_1BasicState.html", null ],
        [ "BlockEndState", "classantlr4_1_1atn_1_1BlockEndState.html", null ],
        [ "BlockStartState", "classantlr4_1_1atn_1_1BlockStartState.html", null ],
        [ "ContextSensitivityInfo", "classantlr4_1_1atn_1_1ContextSensitivityInfo.html", "classantlr4_1_1atn_1_1ContextSensitivityInfo" ],
        [ "DecisionInfo", "classantlr4_1_1atn_1_1DecisionInfo.html", "classantlr4_1_1atn_1_1DecisionInfo" ],
        [ "DecisionState", "classantlr4_1_1atn_1_1DecisionState.html", null ],
        [ "EmptyPredictionContext", "classantlr4_1_1atn_1_1EmptyPredictionContext.html", "classantlr4_1_1atn_1_1EmptyPredictionContext" ],
        [ "EpsilonTransition", "classantlr4_1_1atn_1_1EpsilonTransition.html", "classantlr4_1_1atn_1_1EpsilonTransition" ],
        [ "LexerATNConfig", "classantlr4_1_1atn_1_1LexerATNConfig.html", "classantlr4_1_1atn_1_1LexerATNConfig" ],
        [ "LoopEndState", "classantlr4_1_1atn_1_1LoopEndState.html", null ],
        [ "NotSetTransition", "classantlr4_1_1atn_1_1NotSetTransition.html", null ],
        [ "OrderedATNConfigSet", "classantlr4_1_1atn_1_1OrderedATNConfigSet.html", null ],
        [ "ParseInfo", "classantlr4_1_1atn_1_1ParseInfo.html", "classantlr4_1_1atn_1_1ParseInfo" ],
        [ "ParserATNSimulator", "classantlr4_1_1atn_1_1ParserATNSimulator.html", "classantlr4_1_1atn_1_1ParserATNSimulator" ],
        [ "PrecedencePredicateTransition", "classantlr4_1_1atn_1_1PrecedencePredicateTransition.html", "classantlr4_1_1atn_1_1PrecedencePredicateTransition" ],
        [ "PredicateTransition", "classantlr4_1_1atn_1_1PredicateTransition.html", "classantlr4_1_1atn_1_1PredicateTransition" ],
        [ "PredictionContext", "classantlr4_1_1atn_1_1PredictionContext.html", "classantlr4_1_1atn_1_1PredictionContext" ],
        [ "PredictionContextComparer", "structantlr4_1_1atn_1_1PredictionContextComparer.html", null ],
        [ "PredictionContextHasher", "structantlr4_1_1atn_1_1PredictionContextHasher.html", null ],
        [ "PredictionContextMergeCache", "classantlr4_1_1atn_1_1PredictionContextMergeCache.html", null ],
        [ "PredictionModeClass", "classantlr4_1_1atn_1_1PredictionModeClass.html", null ],
        [ "ProfilingATNSimulator", "classantlr4_1_1atn_1_1ProfilingATNSimulator.html", "classantlr4_1_1atn_1_1ProfilingATNSimulator" ],
        [ "RangeTransition", "classantlr4_1_1atn_1_1RangeTransition.html", null ],
        [ "RuleStartState", "classantlr4_1_1atn_1_1RuleStartState.html", null ],
        [ "RuleStopState", "classantlr4_1_1atn_1_1RuleStopState.html", null ],
        [ "RuleTransition", "classantlr4_1_1atn_1_1RuleTransition.html", "classantlr4_1_1atn_1_1RuleTransition" ],
        [ "SemanticContext", "classantlr4_1_1atn_1_1SemanticContext.html", "classantlr4_1_1atn_1_1SemanticContext" ],
        [ "SetTransition", "classantlr4_1_1atn_1_1SetTransition.html", null ],
        [ "SingletonPredictionContext", "classantlr4_1_1atn_1_1SingletonPredictionContext.html", null ],
        [ "StarBlockStartState", "classantlr4_1_1atn_1_1StarBlockStartState.html", null ],
        [ "StarLoopbackState", "classantlr4_1_1atn_1_1StarLoopbackState.html", null ],
        [ "StarLoopEntryState", "classantlr4_1_1atn_1_1StarLoopEntryState.html", "classantlr4_1_1atn_1_1StarLoopEntryState" ],
        [ "TokensStartState", "classantlr4_1_1atn_1_1TokensStartState.html", null ],
        [ "Transition", "classantlr4_1_1atn_1_1Transition.html", "classantlr4_1_1atn_1_1Transition" ],
        [ "WildcardTransition", "classantlr4_1_1atn_1_1WildcardTransition.html", null ]
      ] ],
      [ "dfa", null, [
        [ "DFA", "classantlr4_1_1dfa_1_1DFA.html", "classantlr4_1_1dfa_1_1DFA" ],
        [ "DFASerializer", "classantlr4_1_1dfa_1_1DFASerializer.html", null ],
        [ "LexerDFASerializer", "classantlr4_1_1dfa_1_1LexerDFASerializer.html", null ]
      ] ],
      [ "misc", null, [
        [ "InterpreterData", "structantlr4_1_1misc_1_1InterpreterData.html", null ],
        [ "InterpreterDataReader", "classantlr4_1_1misc_1_1InterpreterDataReader.html", null ],
        [ "Interval", "classantlr4_1_1misc_1_1Interval.html", "classantlr4_1_1misc_1_1Interval" ],
        [ "IntervalSet", "classantlr4_1_1misc_1_1IntervalSet.html", "classantlr4_1_1misc_1_1IntervalSet" ],
        [ "MurmurHash", "classantlr4_1_1misc_1_1MurmurHash.html", null ],
        [ "Predicate", "classantlr4_1_1misc_1_1Predicate.html", null ]
      ] ],
      [ "tree", null, [
        [ "xpath", null, [
          [ "XPathLexerErrorListener", "classantlr4_1_1tree_1_1xpath_1_1XPathLexerErrorListener.html", null ],
          [ "XPathRuleAnywhereElement", "classantlr4_1_1tree_1_1xpath_1_1XPathRuleAnywhereElement.html", null ],
          [ "XPathRuleElement", "classantlr4_1_1tree_1_1xpath_1_1XPathRuleElement.html", null ],
          [ "XPathTokenAnywhereElement", "classantlr4_1_1tree_1_1xpath_1_1XPathTokenAnywhereElement.html", null ],
          [ "XPathTokenElement", "classantlr4_1_1tree_1_1xpath_1_1XPathTokenElement.html", null ],
          [ "XPathWildcardAnywhereElement", "classantlr4_1_1tree_1_1xpath_1_1XPathWildcardAnywhereElement.html", null ],
          [ "XPathWildcardElement", "classantlr4_1_1tree_1_1xpath_1_1XPathWildcardElement.html", null ]
        ] ],
        [ "AbstractParseTreeVisitor", "classantlr4_1_1tree_1_1AbstractParseTreeVisitor.html", "classantlr4_1_1tree_1_1AbstractParseTreeVisitor" ],
        [ "ErrorNode", "classantlr4_1_1tree_1_1ErrorNode.html", null ],
        [ "ErrorNodeImpl", "classantlr4_1_1tree_1_1ErrorNodeImpl.html", null ],
        [ "IterativeParseTreeWalker", "classantlr4_1_1tree_1_1IterativeParseTreeWalker.html", "classantlr4_1_1tree_1_1IterativeParseTreeWalker" ],
        [ "ParseTree", "classantlr4_1_1tree_1_1ParseTree.html", "classantlr4_1_1tree_1_1ParseTree" ],
        [ "ParseTreeListener", "classantlr4_1_1tree_1_1ParseTreeListener.html", null ],
        [ "ParseTreeProperty", "classantlr4_1_1tree_1_1ParseTreeProperty.html", null ],
        [ "ParseTreeTracker", "classantlr4_1_1tree_1_1ParseTreeTracker.html", null ],
        [ "ParseTreeWalker", "classantlr4_1_1tree_1_1ParseTreeWalker.html", "classantlr4_1_1tree_1_1ParseTreeWalker" ],
        [ "TerminalNode", "classantlr4_1_1tree_1_1TerminalNode.html", "classantlr4_1_1tree_1_1TerminalNode" ],
        [ "TerminalNodeImpl", "classantlr4_1_1tree_1_1TerminalNodeImpl.html", "classantlr4_1_1tree_1_1TerminalNodeImpl" ],
        [ "Trees", "classantlr4_1_1tree_1_1Trees.html", null ]
      ] ],
      [ "ANTLRErrorListener", "classantlr4_1_1ANTLRErrorListener.html", null ],
      [ "ANTLRErrorStrategy", "classantlr4_1_1ANTLRErrorStrategy.html", null ],
      [ "ANTLRFileStream", "classantlr4_1_1ANTLRFileStream.html", null ],
      [ "ANTLRInputStream", "classantlr4_1_1ANTLRInputStream.html", "classantlr4_1_1ANTLRInputStream" ],
      [ "BaseErrorListener", "classantlr4_1_1BaseErrorListener.html", null ],
      [ "BufferedTokenStream", "classantlr4_1_1BufferedTokenStream.html", "classantlr4_1_1BufferedTokenStream" ],
      [ "CancellationException", "classantlr4_1_1CancellationException.html", null ],
      [ "CommonToken", "classantlr4_1_1CommonToken.html", "classantlr4_1_1CommonToken" ],
      [ "CommonTokenFactory", "classantlr4_1_1CommonTokenFactory.html", "classantlr4_1_1CommonTokenFactory" ],
      [ "CommonTokenStream", "classantlr4_1_1CommonTokenStream.html", "classantlr4_1_1CommonTokenStream" ],
      [ "ConsoleErrorListener", "classantlr4_1_1ConsoleErrorListener.html", "classantlr4_1_1ConsoleErrorListener" ],
      [ "DefaultErrorStrategy", "classantlr4_1_1DefaultErrorStrategy.html", "classantlr4_1_1DefaultErrorStrategy" ],
      [ "EmptyStackException", "classantlr4_1_1EmptyStackException.html", null ],
      [ "FailedPredicateException", "classantlr4_1_1FailedPredicateException.html", null ],
      [ "IllegalArgumentException", "classantlr4_1_1IllegalArgumentException.html", null ],
      [ "IllegalStateException", "classantlr4_1_1IllegalStateException.html", null ],
      [ "IndexOutOfBoundsException", "classantlr4_1_1IndexOutOfBoundsException.html", null ],
      [ "InputMismatchException", "classantlr4_1_1InputMismatchException.html", null ],
      [ "InterpreterRuleContext", "classantlr4_1_1InterpreterRuleContext.html", "classantlr4_1_1InterpreterRuleContext" ],
      [ "IOException", "classantlr4_1_1IOException.html", null ],
      [ "Lexer", "classantlr4_1_1Lexer.html", "classantlr4_1_1Lexer" ],
      [ "LexerInterpreter", "classantlr4_1_1LexerInterpreter.html", "classantlr4_1_1LexerInterpreter" ],
      [ "LexerNoViableAltException", "classantlr4_1_1LexerNoViableAltException.html", null ],
      [ "NoViableAltException", "classantlr4_1_1NoViableAltException.html", null ],
      [ "NullPointerException", "classantlr4_1_1NullPointerException.html", null ],
      [ "ParseCancellationException", "classantlr4_1_1ParseCancellationException.html", null ],
      [ "Parser", "classantlr4_1_1Parser.html", "classantlr4_1_1Parser" ],
      [ "ParserInterpreter", "classantlr4_1_1ParserInterpreter.html", "classantlr4_1_1ParserInterpreter" ],
      [ "ParserRuleContext", "classantlr4_1_1ParserRuleContext.html", "classantlr4_1_1ParserRuleContext" ],
      [ "ProxyErrorListener", "classantlr4_1_1ProxyErrorListener.html", null ],
      [ "Recognizer", "classantlr4_1_1Recognizer.html", "classantlr4_1_1Recognizer" ],
      [ "RuleContext", "classantlr4_1_1RuleContext.html", "classantlr4_1_1RuleContext" ],
      [ "RuleContextWithAltNum", "classantlr4_1_1RuleContextWithAltNum.html", "classantlr4_1_1RuleContextWithAltNum" ],
      [ "RuntimeException", "classantlr4_1_1RuntimeException.html", null ],
      [ "Token", "classantlr4_1_1Token.html", "classantlr4_1_1Token" ],
      [ "TokenFactory", "classantlr4_1_1TokenFactory.html", "classantlr4_1_1TokenFactory" ],
      [ "TokenSource", "classantlr4_1_1TokenSource.html", "classantlr4_1_1TokenSource" ],
      [ "TokenStreamRewriter", "classantlr4_1_1TokenStreamRewriter.html", "classantlr4_1_1TokenStreamRewriter" ],
      [ "UnsupportedOperationException", "classantlr4_1_1UnsupportedOperationException.html", null ],
      [ "WritableToken", "classantlr4_1_1WritableToken.html", null ]
    ] ],
    [ "antlrcpp", null, [
      [ "Any", "structantlrcpp_1_1Any.html", null ],
      [ "Arrays", "classantlrcpp_1_1Arrays.html", null ],
      [ "BitSet", "classantlrcpp_1_1BitSet.html", null ],
      [ "FinalAction", "structantlrcpp_1_1FinalAction.html", null ],
      [ "SingleWriteMultipleReadLock", "classantlrcpp_1_1SingleWriteMultipleReadLock.html", null ]
    ] ],
    [ "curl", "namespacecurl.html", "namespacecurl" ],
    [ "hash_table", null, [
      [ "HashTable", "classhash__table_1_1HashTable.html", "classhash__table_1_1HashTable" ]
    ] ],
    [ "loguru", null, [
      [ "Callback", "structloguru_1_1Callback.html", null ],
      [ "decay_char_array", "structloguru_1_1decay__char__array.html", null ],
      [ "decay_char_array< const char(&)[N]>", "structloguru_1_1decay__char__array_3_01const_01char_07_6_08_0fN_0e_4.html", null ],
      [ "EcEntryBase", "classloguru_1_1EcEntryBase.html", null ],
      [ "EcEntryData", "classloguru_1_1EcEntryData.html", null ],
      [ "LogScopeRAII", "classloguru_1_1LogScopeRAII.html", null ],
      [ "make_const_ptr", "structloguru_1_1make__const__ptr.html", null ],
      [ "make_const_ptr< T * >", "structloguru_1_1make__const__ptr_3_01T_01_5_01_4.html", null ],
      [ "make_ec_type", "structloguru_1_1make__ec__type.html", null ],
      [ "Message", "structloguru_1_1Message.html", null ],
      [ "Options", "structloguru_1_1Options.html", null ],
      [ "Signal", "structloguru_1_1Signal.html", null ],
      [ "StringStream", "structloguru_1_1StringStream.html", null ],
      [ "Text", "classloguru_1_1Text.html", null ]
    ] ],
    [ "Mandelbrot", "namespaceMandelbrot.html", "namespaceMandelbrot" ],
    [ "std", null, [
      [ "hash< ATNConfig >", "structstd_1_1hash_3_01ATNConfig_01_4.html", null ],
      [ "hash< IntervalSet >", "structstd_1_1hash_3_01IntervalSet_01_4.html", null ],
      [ "hash< SemanticContext >", "structstd_1_1hash_3_01SemanticContext_01_4.html", null ],
      [ "hash< std::vector< Ref< ATNConfig > > >", "structstd_1_1hash_3_01std_1_1vector_3_01Ref_3_01ATNConfig_01_4_01_4_01_4.html", null ]
    ] ],
    [ "Template", "namespaceTemplate.html", "namespaceTemplate" ],
    [ "tool", null, [
      [ "Control", "classtool_1_1Control.html", null ],
      [ "State", "classtool_1_1State.html", "classtool_1_1State" ]
    ] ]
];