name: Checking pipeline
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    container:
        image: searchseco/controller
        env:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            worker_name: check-action:${{ github.repository }}
        options: --entrypoint ""
    steps:
      - name: Checkupload
        run: |
             pwd
             ls
             /controller/build/searchseco check https://github.com/${{ github.repository }} -b ${{ github.ref }}